import UserSessionModel from "./session";
import UserModel from "./user";
import MediaModel from "./media";
import IndustriesModel from "./industries";
import CityModel from "./city";
import JobModel from "./jobs";
import SmtpSettingModel from "./smtp";
import ManageContentModel from "./manageContent";
import ManageKeyModel from "./manageKey";
import EmployerModel from "./employer";
import JobDocumentModel from "./jobDocument";
import CompanyImageModel from "./companyImage";
import ApplicationModel from "./jobApplication";
import AppoinmentModel from "./appoinment";
import JobImagesModel from "./jobImages";
import JobTypesModel from "./jobType";
import ContactModel from "./contact";
import ApplicationTipModel from "./applicationTip";
import JobAlertContentModel from "./jobAlertContent";
import JobBannerModel from "./jobBanner";
import FederalStatesModel from "./federalState";
import TrainingsModel from "./training";
import BeginningsModel from "./beginning";
import _ManageHomeContentModel from "./homeContent";
import _RegionsModel from "./regions";
import _JobMarketContentModel from "./jobMarketContent";
import _ApplyFormContentModel from "./applyFormContent";
import _CompanyContent from "./companyContent";
import _SideBarContentModel from "./sideBarContent";
import _FaqContentModel from "./FaqContent";
import _AboutContentModel from "./aboutContent";
import _JobMagazineContentModel from "./magazineContent";
import _ContactUsContentModel from "./contactUsContent";
import _JobWallContentModel from "./jobWallContent";
import _HomePageContentModel from "./homePageContent";
import _EmailContentModel from "./emailContent";
import _TabsModel from "./tabs";
import _ManageCitiesContentModel from "./manageCityContent";
import FooterImagesModel from "./footerImages";
import MapDetailModel from "./map";
import ContactFormModel from "./contactForm";
import ManagedUserModel from "./managedUser";
import ManagedEmployeeModel from "./managedEmployee";

export const userSessionModel = UserSessionModel;
export const userModel = UserModel;
export const mediaModel = MediaModel;
export const industriesModel = IndustriesModel;
export const cityModel = CityModel;
export const jobModel = JobModel;
export const smtpSettingModel = SmtpSettingModel;
export const manageContentModel = ManageContentModel;
export const manageKeyModel = ManageKeyModel;
export const employerModel = EmployerModel;
export const jobDocumentModel = JobDocumentModel;
export const companyImageModel = CompanyImageModel;
export const applicationModel = ApplicationModel;
export const appoinmentModel = AppoinmentModel;
export const jobImagesModel = JobImagesModel;
export const jobTypesModel = JobTypesModel;
export const contactModel = ContactModel;
export const applicationTip = ApplicationTipModel;
export const jobAlertContentModel = JobAlertContentModel;
export const jobBannerModel = JobBannerModel;
export const federalStateModel = FederalStatesModel;
export const trainingsModel = TrainingsModel;
export const beginningsModel = BeginningsModel;
export const manageHomeContentModel = _ManageHomeContentModel;
export const regionModel = _RegionsModel;
export const jobMarketContentModel = _JobMarketContentModel;
export const applyFormContentModel = _ApplyFormContentModel;
export const companyContentModel = _CompanyContent;
export const sideBarContentModel = _SideBarContentModel;
export const faqContentModel = _FaqContentModel;
export const aboutContentModel = _AboutContentModel;
export const jobMagazineContentModel = _JobMagazineContentModel;
export const contactUsContentModel = _ContactUsContentModel;
export const jobWallContentModel = _JobWallContentModel;
export const homePageContentModel = _HomePageContentModel;
export const emailContentModel = _EmailContentModel;
export const TabsModel = _TabsModel;
export const ManageCitiesContentModel = _ManageCitiesContentModel;
export const footerImagesModel = FooterImagesModel;
export const mapDetailModel = MapDetailModel;
export const contactFormDaynamic = ContactFormModel;
export const managedUserModel = ManagedUserModel;
export const managedEmployeeModel = ManagedEmployeeModel;
